# Code generated by protoc-gen-twirp_ruby 1.9.0, DO NOT EDIT.
require 'twirp'
require_relative 'customers_pb.rb'

class CustomerServiceService < Twirp::Service
  service 'CustomerService'
  rpc :GetAll, Empty, CustomerList, :ruby_method => :get_all
  rpc :Get, CustomerRequestId, Customer, :ruby_method => :get
  rpc :Insert, Customer, Customer, :ruby_method => :insert
  rpc :Update, Customer, Customer, :ruby_method => :update
  rpc :Remove, CustomerRequestId, Empty, :ruby_method => :remove
end

class CustomerServiceClient < Twirp::Client
  client_for CustomerServiceService
end
